version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:80" 
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./styles.css:/usr/share/nginx/html/styles.css:ro
      - ./app.js:/usr/share/nginx/html/app.js:ro

